Merge feature/DLOB-3223-Add-fileDownloadUrl-in-DJSF-Spec
CN-Consult/djsf pull request #7
Opened 2023-04-17 07:47 UTC by fabian-bickel

Add fileDownloadUrl in DJSF spec.

2023-04-17 10:06 UTC, ylapp1 commented
Just a question:
Is it correct that we need to increase the DJSF schema-version in the Motion-Code so that OnBoard knows that the new `fileDownloadUrl` property exists in the schedule JSON data?
https://github.com/CN-Consult/DiLoc/blob/6fa7b04f9ca265330f4398aa1cb12f2d7d9b9c49/backend/lib/rail/subsystems/mpi/scheduleformats/djsf/json/schedule.php#L48-L58

If yes we should adjust the schema description to tell that it is version `2.4.3` or `2.5.0` now
https://github.com/CN-Consult/djsf/blob/60e482393895dd5dd05f76dc074d4a7f1118f286/djsf.json#L5

And a changelog description should be added to README: https://github.com/CN-Consult/djsf/blob/60e482393895dd5dd05f76dc074d4a7f1118f286/README.md?plain=1#L88-L89

2023-05-11 07:13 UTC, Shyru requested changes
I would suggest to enhance the documentation a bit more.

2023-05-11 07:13 UTC, Shyru commented on djsf.json
> +					"description": "The URL with path to the API endpoint to download schedule audio files"
Should we document here, how the filename of the file to be downloaded is appended to the url?

2023-05-22 06:31 UTC, Shyru approved these changes
Looks good!

2023-05-22 06:34 UTC, merged